### ISSUE TITLE
[Bug]: Allies not saved between restarts

### ISSUE THREAD

**Issue by Trent2087** [terrarium-earth/Argonauts#13]
### Bug Description

When the server restarts allies are wiped. I assume the data is not getting saved.
Also you cannot remove allies as it gives the error that the player is not in a guild.
```
/guild allies add Sir_Cappy
Sir_Cappy is now allied to your guild
/guild allies remove Sir_Cappy
The player is not in a guild.
```

### How to Reproduce?

Add guild ally.
Restart server.
Player is no longer an ally.

### Version

1.0.8

### Mod Loader Version

1.20.1 - 0.14.25

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by ThatGravyBoat** [comment]
Fixed in dev

**Comment by Trent2087** [comment]
Backport to 1.20.1 please :)

**Comment by AlexNijjar** [comment]
Done v1.0.9
