### ISSUE TITLE
[Feature Request]: Placeholder API support

### ISSUE THREAD

**Issue by pbone64** [terrarium-earth/Argonauts#6]
### Is your feature request related to a problem?

Currently, there is no way to display the current guild in the player list or chat formatted by mods such as [Styled Chat](https://modrinth.com/mod/styled-chat).

### Solution(s)

The most widely-used system to allow for chat formatting using data provided by mods is, to my knowledge, [Placeholder API](https://modrinth.com/mod/placeholder-api). I propose the following placeholders:
- `%player:argonauts_guild`: returns the name of the player's guild.
- `%player:argonauts_party`: returns the name of player's party

### Describe alternatives you've considered

There may be other similar APIs that I am not familiar with.

### Mod Version

N/A

### Mod Loader Version

N/A

### Mod Loader

N/A

**Comment by AlexNijjar** [comment]
I've added Placeholder API support.
There's `argonauts:guild` for the guild name and `argonauts:party` for the party name. Placeholder formatting is also now available for Message of the Day messages.
