### ISSUE TITLE
[Bug]: REI Buttons not appearing on Forge

### ISSUE THREAD

**Issue by waddon1** [terrarium-earth/Argonauts#7]
### Bug Description

I saw that REI buttons were added a while ago, however they don't seem to appear in the forge version. I tried them on Quilt and it worked. Not sure if it's conflicting with something else in my modpack

### How to Reproduce?

1. Enter world
2. Open inventory
3. Go into plus in bottom right
4. No buttons

### Expected Behavior

Project Odyssey buttons appear

### Version

1.0.2

### Mod Loader Version

47.1.3

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by AlexNijjar** [comment]
Fixed in 8097103
