### ISSUE TITLE
[Feature Request]: Maintain a cache on the client of parties and guilds

### ISSUE THREAD

**Issue by mysticdrew** [terrarium-earth/Argonauts#9]
### Is your feature request related to a problem?

Working on adding support to https://github.com/mysticdrew/journeymap-teams. 
On the client there is no API, so I cannot retrieve a list of parties and guilds. 
It would be nice if Argonauts could update a client cache on guild/party updates. 

Reasoning
On the client it would be able to color player Icons and Names on the map, can also hide other parties/teams. 

I also think other mods that use your API would benefit from a client api in Argonauts. 

### Solution(s)

maybe something like this
```
        var localPlayer = Minecraft.getInstance().player;
        var localGuild = GuildApi.ClientAPI.get(localPlayer);
        var remoteGuild = GuildApi.ClientAPI.get(remotePlayer);

        var localParty = PartyApi.ClientAPI.get(localPlayer);
        var remoteParty = PartyApi.ClientAPI.get(remotePlayer);
```

### Mod Version

any

### Mod Loader Version

1.20.1

### Mod Loader

N/A

**Comment by AlexNijjar** [comment]
Added in v1.0.5 via `GuildClientApi` and `PartyClientApi`
Here's an example. Let me know if this works

```java
var localPlayer = Minecraft.getInstance().player;

var guild = GuildClientApi.API.get(guildId);
var localGuild = GuildClientApi.API.getPlayerGuild(localPlayer);
var remoteGuild = GuildClientApi.API.getPlayerGuild(remotePlayer);

var party = PartyClientApi.API.get(partyId);
var localParty = PartyClientApi.API.getPlayerParty(localPlayer);
var remoteParty = PartyClientApi.API.getPlayerParty(remotePlayer);
```

**Comment by mysticdrew** [comment]
That looks perfect! Thank you.
